### ISSUE TITLE
`/var/lib/containers` conflicts with system containers

### ISSUE THREAD

**Issue by giuseppe** [projectatomic/container-storage-setup#231]
system containers install under `/var/lib/containers/atomic` and they need to use the same file system as `/ostree/repo` so that hard links from the OSTree repository can be used.

Now `container-storage-setup` is using by default `/var/lib/containers` for creating the storage and that breaks the assumption behind system containers for sharing the storage with OSTree.

Should the default be `/var/lib/containers/storage`?

@rhatdan

**Comment by rhvgoyal** [comment]
Where do we use /var/lib/containers? Are you referring to man page where we give an example where a logical volume can be mounted? That's just an example and we can change it.

We will create /var/lib/container-storage-setup though to store metadata of our own.

**Comment by giuseppe** [comment]
I was referring to the man page and to the `container-storage-setup.conf`file:
```
# CONTAINER_ROOT_LV_MOUNT_PATH="/var/lib/containers"
```
uncommenting this line will probably be the first choice when someone wants to use it

**Comment by rhvgoyal** [comment]
@giuseppe we are not creating storage under /var/lib/containers. Assumption is that /var/lib/containers is the directory where container runtime will store its metadata. So we can mount something on /var/lib/containers so that metadata is not stored on rootfs but goes to separate disk.

So /var/lib/containers/storage will not fit.

May be we can put /var/lilb/container-runtime/ for now as an example.

@rhatdan WDYT?

**Comment by rhatdan** [comment]
Yes this man page was referring more to where ocid is storing it storage.  Container-storage-setup is just taking input from the packagers about where it should create storage.  We can change the example to be /var/lib/containers/storage if you want @giuseppe .

**Comment by giuseppe** [comment]
yes thanks.  If it can help, I can prepare a PR

**Comment by rhatdan** [comment]
SGTM
